//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datwise_Tech_Lead_Home_Assignment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DatwiseDBEntities : DbContext
    {
        public DatwiseDBEntities()
            : base("name=DatwiseDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditLog> AuditLog { get; set; }
        public virtual DbSet<ReportsData> ReportsData { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    
        public virtual ObjectResult<sp_GetReportPaged_Result> sp_GetReportPaged(Nullable<int> pageNumber, Nullable<int> pageSize, string categoryFilter, string regionFilter, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var categoryFilterParameter = categoryFilter != null ?
                new ObjectParameter("CategoryFilter", categoryFilter) :
                new ObjectParameter("CategoryFilter", typeof(string));
    
            var regionFilterParameter = regionFilter != null ?
                new ObjectParameter("RegionFilter", regionFilter) :
                new ObjectParameter("RegionFilter", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetReportPaged_Result>("sp_GetReportPaged", pageNumberParameter, pageSizeParameter, categoryFilterParameter, regionFilterParameter, fromDateParameter, toDateParameter);
        }
    }
}
